timetracking/config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'site#home'
  get '/contact', to: 'site#contact'
  

 resources :projects, only: [:index, :show, :new, :create] do
 resources :time_entries, except: [:show]

end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

timetracking/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

timetracking/app/models/project.rb
 class Project < ApplicationRecord
 	has_many :time_entries
 
 	def self.clean_old
 		old_project = Project.where('created_at < ?', Time.now - 2.days)
 		old_project.destroy_all
 	end
end

timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord
	belongs_to :project
	validates :hours, numericality: true
	validates :date	, presence: true, uniqueness: true
	validates :hours, presence: true, uniqueness: true
	validates :minutes, presence: true, uniqueness: true
	validates_associated :project
end


#the_entry = TimeEntry.create{
# 	:hours => 1
# 	:minutes => 45
# 	:comment => "Did stuff",
# 	:date => Time.now
# 	:project_id => 1)
# 					^
# 					|	
# 		The id of the project tp associate to

timetracking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects_array = Project.order(created_at:"desc")
									.limit(10)

		render "index"
	end

	def show 
		@my_project = Project.find(params[:id])

		render "show"
	end

	def new 
		@my_project =Project.new
			render "new"
	end

	def create
		@my_project = Project.new(
			:name => params[:project][:name],
			:description => params[:project][:description])
		@my_project.save

		redirect_to "/projects/#{@my_project.id}"
	end
end

timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		render 'home' #name of the view template
	end

	def contact
		render 'contact'
	end

	def projects
		render 'projects'

	end

	


end

timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	def index
		@my_project = Project.find(params[:project_id])
		@my_entries = @my_project.time_entries

		render "index"
	end


	def new
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.new

		render "new"
	end

	def create
		
		@my_project = Project.find(params[:project_id])
		
		@my_entry = @my_project.time_entries.new(entry_params)

			if @my_entry.save
				flash[:notice] = "Project created successfully" 
				redirect_to project_time_entries_path
			else 
				redirect_to new_project_time_entry_path
			end
		end	
	




	def edit
		@my_project = Project.find params[:project_id]
		@my_entry = TimeEntry.find params[:id]

		render "edit"	
		
	end

	def update
		@my_project = Project.find_by(id: params[:project_id])
		@my_entry = @my_project.time_entries.find_by(id: params[:id])

		if @my_entry.update(entry_params)
			redirect_to action: "index",controller: 'time_entries',
		project_id:@my_project.id
	else
		render 'edit'
	end
end

	def destroy
		@my_project = Project.find(params[:project_id])
		@my_entry = @my_project.time_entries.find(params[:id])

		@my_entry.destroy

		redirect_to project_time_entries_path(@my_project)
	end






#add any new methods ABOVE	 the "private"

	private

	def entry_params

		# {hours: params[:time_entry][:hours],
		#  minutes: params[:time_entry][:minutes],
		#  date: params[:time_entry][:date],
		#  comment: params[:time_entry][:date]}

		params.require(:time_entry).permit(:hours, :minutes, :date, :comment)
	end
end

timetracking/app/helpers/application_helper.rb
module ApplicationHelper
end

timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

timetracking/app/helpers/site_helper.rb
module SiteHelper
end

timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <footer>
  		<p>Made with &hearts; at Ironhack</p>
  </footer>
</html>

timetracking/app/views/partials/_sign_up.html.erb
<!-- app/views/_sign_up.html.erb -->

<div>
	<h2>Sign up now</h2>
		<a href="#">
		Sign Up
		</a>
</div>

timetracking/app/views/projects/index.html.erb
<h2>List of projects</h2>

<ul>
	<% @projects_array.each do |the_project|%>
		<li>

			<a href="/projects/<%= the_project.id %>">
			<%=the_project.name%>
			</a>
			<% if the_project.description != nil%>
			 - <%= the_project.description %>
			 	<% end -%>
		</li>
	<% end %>
</ul>		


<a href="/projects">Back to list</a>

timetracking/app/views/projects/new.html.erb
<h1>Add a project</h1>
<%= form_for @my_project do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_area :description%>

	<%= f.button %>
<% end -%>

timetracking/app/views/projects/show.html.erb
<h2><%= @my_project.name %> </h2>

<h3> Details Page</h3>

<p ><%= @my_project.description%></p>

<a href="/projects/<%= @my_project.id %>/time_entries">
	See time entries
</a>

timetracking/app/views/site/contact.html.erb
<h1>Don't send me any spam !!!!</h1>


<p>JohanConMan666@gmail.com</p>

timetracking/app/views/site/home.html.erb
<h1>Welcome to this time tracking tool</h1>

<%render("partials/_sign_up") %>
<h1>Welcome to this time tracking tool</h1>

<p>Ironhack powered</p>

<a href="JohanConMan666@gmail.com">Contact Info!</a>
<a href="http://youthinc.tumblr.com/post/29945734697" alt="CrazyThrow!">

timetracking/app/views/site/show.html.erb
<h2><%= @my_project.name %> </h2>

<h3> Details PAge</h3>

<p ><%= @my_project.description%></p>

timetracking/app/views/time_entries/_form.html.erb
<% if @my_entry.errors.any? %>
	<ul>
		<%@my_entry.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %> </li>
			<% end %>
	</ul>
<% end %>

<%= form_for [@my_project, @my_entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours, size: 4 %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes, size: 4 %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date, size: 4 %>
	<br>
	<%= f.label  :comment%>
	<%= f.text_area :comment %>
	<br>
	<%= f.button %>
	<%= link_to 'Cancel', project_time_entries_path(@my_project) %>
<% end %>

timetracking/app/views/time_entries/edit.html.erb
<h2> Edit a new time entry in <%= @my_project.name %> project </h2>
<% render "form" %>

timetracking/app/views/time_entries/index.html.erb
<h1><%= @my_project.name%></h1>

<% if flash[:notice] %> 
  <%= flash[:notice] %> 
<% end %> 


<ul>
	<% @my_entries.each do |entry| %>
	<li>
		<%= entry.hours %> h
		<%= entry.minutes%> m -
		<%= entry.date %>

		<p> <%= entry.comment %></p>
	
		<a href="/projects/<%= @my_project.id %>/time_entries/<%= entry.id%>/edit">
		edit
		</a>

		<%= link_to('Delete',project_time_entry_path(@my_project,entry), method:
		'delete', data: {confirm: 'Are you sure?'})%>

	</li>

	<% end -%>

</ul>

<a href="/projects/<%= @my_project.id %>/time_entries/new">Add time entry to  <%= @my_project.name %></a>

timetracking/app/views/time_entries/new.html.erb
<h2>
	Add a new time entry for <%=@my_project.name%>
</h2>

<%= render "form"%>